version: '3'

services:
  app:
    build: .
    container_name: taskly.app
    restart: on-failure
    environment:
      - DB_URI=mongodb://db:27017/taskly
    depends_on:
      - db
    ports:
      - 3040:3040

  db:
    image: mongo:latest
    container_name: taskly.db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod
