version: '3'

services:
  app:
    build: .
    container_name: taksly.app
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    image: mongo:latest
    container_name: taksly.db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod
